FROM php:7.3-fpm-buster

RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections

# Create man1 directory - required by openjdk-11-jdk package
RUN mkdir -p /usr/share/man/man1

RUN apt-get update -y \
    && apt-get upgrade -y \
    && apt install -y ant
