version: '3.5'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.ci
    container_name: my_test_container2
    environment:
      - APPLICATION_ENV=development
    volumes:
      - .:/var/www
  mysql:
    image: mariadb:10.2.23
    container_name: mysql.ddd
    hostname: mysql.ddd
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./docker/mariadb/conf.d:/etc/mariadb/conf.d
      - ./docker/mariadb/initdb.d:/docker-entrypoint-initdb.d

