version: '3.5'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.ci
    container_name: my_test_container2
    environment:
      - APPLICATION_ENV=development
    volumes:
      - .:/var/www
